forge 'forge.puppetlabs.com'

mod 'puppetlabs/apache'
mod 'puppetlabs/concat'
mod 'puppetlabs/firewall'
mod 'puppetlabs/inifile'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/xinetd'
mod 'puppetlabs/ruby'

mod 'saz/ssh'
mod 'zack/r10k'
mod 'stahnma/epel'

# Foreman and dependencies
mod 'adrien/alternatives'
mod 'puppetlabs/apt'
mod 'puppetlabs/puppetdb'
mod 'theforeman/concat_native'
mod 'theforeman/dhcp'
mod 'theforeman/dns'
mod 'theforeman/foreman'
mod 'theforeman/foreman_proxy'
mod 'theforeman/git'
mod 'theforeman/puppet'
mod 'theforeman/tftp'
