## \file    modules/apacheplus/manifests/vhost.pp
#  \author  Scott Wales <scott.wales@unimelb.edu.au>
#
#  Copyright 2014 ARC Centre of Excellence for Climate Systems Science
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# An extension of puppetlabs/apache that supports defines for individual
# locations.
define apacheplus::vhost (
    $docroot,
    $virtual_docroot             = undef,
    $port                        = undef,
    $ip                          = undef,
    $ip_based                    = undef,
    $add_listen                  = undef,
    $docroot_owner               = undef,
    $docroot_group               = undef,
    $docroot_mode                = undef,
    $serveradmin                 = undef,
    $ssl                         = undef,
    $ssl_cert                    = undef,
    $ssl_key                     = undef,
    $ssl_chain                   = undef,
    $ssl_ca                      = undef,
    $ssl_crl_path                = undef,
    $ssl_crl                     = undef,
    $ssl_certs_dir               = undef,
    $ssl_protocol                = undef,
    $ssl_cipher                  = undef,
    $ssl_honorcipherorder        = undef,
    $ssl_verify_client           = undef,
    $ssl_verify_depth            = undef,
    $ssl_options                 = undef,
    $ssl_proxyengine             = undef,
    $priority                    = undef,
    $default_vhost               = undef,
    $servername                  = undef,
    $serveraliases               = undef,
    $options                     = undef,
    $override                    = undef,
    $directoryindex              = undef,
    $vhost_name                  = undef,
    $logroot                     = undef,
    $log_level                   = undef,
    $access_log                  = undef,
    $access_log_file             = undef,
    $access_log_pipe             = undef,
    $access_log_syslog           = undef,
    $access_log_format           = undef,
    $access_log_env_var          = undef,
    $aliases                     = undef,
    $directories                 = undef,
    $error_log                   = undef,
    $error_log_file              = undef,
    $error_log_pipe              = undef,
    $error_log_syslog            = undef,
    $error_documents             = undef,
    $fallbackresource            = undef,
    $scriptalias                 = undef,
    $scriptaliases               = undef,
    $proxy_dest                  = undef,
    $proxy_pass                  = undef,
    $suphp_addhandler            = undef,
    $suphp_engine                = undef,
    $suphp_configpath            = undef,
    $php_admin_flags             = undef,
    $php_admin_values            = undef,
    $no_proxy_uris               = undef,
    $redirect_source             = undef,
    $redirect_dest               = undef,
    $redirect_status             = undef,
    $redirectmatch_status        = undef,
    $redirectmatch_regexp        = undef,
    $rack_base_uris              = undef,
    $headers                     = undef,
    $request_headers             = undef,
    $rewrites                    = undef,
    $rewrite_base                = undef,
    $rewrite_rule                = undef,
    $rewrite_cond                = undef,
    $setenv                      = undef,
    $setenvif                    = undef,
    $block                       = undef,
    $ensure                      = undef,
    $wsgi_application_group      = undef,
    $wsgi_daemon_process         = undef,
    $wsgi_daemon_process_options = undef,
    $wsgi_import_script          = undef,
    $wsgi_import_script_options  = undef,
    $wsgi_process_group          = undef,
    $wsgi_script_aliases         = undef,
    $custom_fragment             = undef,
    $itk                         = undef,
    $action                      = undef,
    $fastcgi_server              = undef,
    $fastcgi_socket              = undef,
    $fastcgi_dir                 = undef,
    $additional_includes         = undef,
    $apache_version              = undef,
    $suexec_user_group           = undef,
) {
  if ! defined(Class['apache']) {
    fail('You must include the apache class first')
  }

  # Use the same config location as puppetlabs/apache
  $filename = regsubst($name, ' ', '_', 'G')
  $config = "${::apache::vhost_dir}/${filename}.locations"

  # Add the include path to the custom_fragment
  $custom_include = "include ${config}\n${custom_fragment}"

  concat {$config:
    ensure => present,
    notify => Class['apache::service'],
  }
  concat::fragment {"${name}-header":
    target  => $config,
    content => '# Managed by puppet',
    order   => '01',
  }

  apache::vhost {$name:
    custom_fragment             => $custom_include,

    docroot                     => $docroot,
    virtual_docroot             => $virtual_docroot,
    port                        => $port,
    ip                          => $ip,
    ip_based                    => $ip_based,
    add_listen                  => $add_listen,
    docroot_owner               => $docroot_owner,
    docroot_group               => $docroot_group,
    docroot_mode                => $docroot_mode,
    serveradmin                 => $serveradmin,
    ssl                         => $ssl,
    ssl_cert                    => $ssl_cert,
    ssl_key                     => $ssl_key,
    ssl_chain                   => $ssl_chain,
    ssl_ca                      => $ssl_ca,
    ssl_crl_path                => $ssl_crl_path,
    ssl_crl                     => $ssl_crl,
    ssl_certs_dir               => $ssl_certs_dir,
    ssl_protocol                => $ssl_protocol,
    ssl_cipher                  => $ssl_cipher,
    ssl_honorcipherorder        => $ssl_honorcipherorder,
    ssl_verify_client           => $ssl_verify_client,
    ssl_verify_depth            => $ssl_verify_depth,
    ssl_options                 => $ssl_options,
    ssl_proxyengine             => $ssl_proxyengine,
    priority                    => $priority,
    default_vhost               => $default_vhost,
    servername                  => $servername,
    serveraliases               => $serveraliases,
    options                     => $options,
    override                    => $override,
    directoryindex              => $directoryindex,
    vhost_name                  => $vhost_name,
    logroot                     => $logroot,
    log_level                   => $log_level,
    access_log                  => $access_log,
    access_log_file             => $access_log_file,
    access_log_pipe             => $access_log_pipe,
    access_log_syslog           => $access_log_syslog,
    access_log_format           => $access_log_format,
    access_log_env_var          => $access_log_env_var,
    aliases                     => $aliases,
    directories                 => $directories,
    error_log                   => $error_log,
    error_log_file              => $error_log_file,
    error_log_pipe              => $error_log_pipe,
    error_log_syslog            => $error_log_syslog,
    error_documents             => $error_documents,
    fallbackresource            => $fallbackresource,
    scriptalias                 => $scriptalias,
    scriptaliases               => $scriptaliases,
    proxy_dest                  => $proxy_dest,
    proxy_pass                  => $proxy_pass,
    suphp_addhandler            => $suphp_addhandler,
    suphp_engine                => $suphp_engine,
    suphp_configpath            => $suphp_configpath,
    php_admin_flags             => $php_admin_flags,
    php_admin_values            => $php_admin_values,
    no_proxy_uris               => $no_proxy_uris,
    redirect_source             => $redirect_source,
    redirect_dest               => $redirect_dest,
    redirect_status             => $redirect_status,
    redirectmatch_status        => $redirectmatch_status,
    redirectmatch_regexp        => $redirectmatch_regexp,
    rack_base_uris              => $rack_base_uris,
    headers                     => $headers,
    request_headers             => $request_headers,
    rewrites                    => $rewrites,
    rewrite_base                => $rewrite_base,
    rewrite_rule                => $rewrite_rule,
    rewrite_cond                => $rewrite_cond,
    setenv                      => $setenv,
    setenvif                    => $setenvif,
    block                       => $block,
    ensure                      => $ensure,
    wsgi_application_group      => $wsgi_application_group,
    wsgi_daemon_process         => $wsgi_daemon_process,
    wsgi_daemon_process_options => $wsgi_daemon_process_options,
    wsgi_import_script          => $wsgi_import_script,
    wsgi_import_script_options  => $wsgi_import_script_options,
    wsgi_process_group          => $wsgi_process_group,
    wsgi_script_aliases         => $wsgi_script_aliases,
    itk                         => $itk,
    action                      => $action,
    fastcgi_server              => $fastcgi_server,
    fastcgi_socket              => $fastcgi_socket,
    fastcgi_dir                 => $fastcgi_dir,
    additional_includes         => $additional_includes,
    apache_version              => $apache_version,
    suexec_user_group           => $suexec_user_group,
  }
}
